apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: app
        image: darshankp1/myimage2:v1
        ports:
        - containerPort: 3000